#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# YAML validated using http://www.yamllint.com/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: false

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
 
before_install:
  - Rscript --version
  - Rscript -e 'install.packages("remotes")'
  - Rscript -e 'remotes::install_github("HenrikBengtsson/fake-GLAD")'

before_script:
  - R --vanilla -e "sessionInfo()" -e "capabilities()" -e "sapply(c(physical_cores = FALSE, logical_cores = TRUE), parallel::detectCores)" -e "if (require(RhpcBLASctl, quietly=TRUE)) utils::str(list(get_num_procs = get_num_procs(), get_num_cores = get_num_cores(), blas_get_num_procs = blas_get_num_procs(), omp_get_num_procs = omp_get_num_procs(), omp_get_max_threads = omp_get_max_threads()))"
  - export _R_CHECK_TIMINGS_=0

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
      env:
        - R_KEEP_PKG_SOURCE=yes
        - _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=true
        - _R_S3_METHOD_LOOKUP_USE_TOPENV_AS_DEFENV_=true
        - _R_CHECK_CONNECTIONS_LEFT_OPEN_=true
        - _R_CHECK_LENGTH_1_CONDITION_=true
        - _R_CHECK_LENGTH_1_LOGIC2_=true
        - _R_CLASS_MATRIX_ARRAY_=true
    - os: osx
      r: oldrel
    - os: osx
      r: release
    - os: linux
      r: release
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      r_packages:
        - covr
      after_success:
        - Rscript -e 'covr::codecov(quiet=FALSE)'
      env: NB='w/ covr' ## Just a label

addons:
  apt:
    packages:
      - libfftw3-dev  ## Needed by Bioc package fftwtools
#      - libgsl-dev    ## Needed by Bioc package GLAD (need whitelisting)

bioc_packages:
  - BiocManager

notifications:
  email:
    on_success: change
    on_failure: change
