/***********************************************************************
 * The file was automatically generated by aroma.affymetrix.
 * Do not edit this file!
 ***********************************************************************/

explorer.onLoad = function() {
  /* Detected chromosomes */
  this.setChromosomes(new Array('01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','X','Y'));

  /* Detected chip types */
  this.setChipTypes(new Array('Mapping10K_Xba142'));

  /* Samples */
  this.setSamples({'0001-7,10K,15-08-2006':'0001-7', '0002-10,10K,15-08-2006':'0002-10', '0004-13,10K,15-08-2006':'0004-13', '0005-14,10K,15-08-2006':'0005-14', '0007-18,10K,16-08-2006':'0007-18', '0008-19,10K,16-08-2006':'0008-19'});
 
  /* Detected sets */
  this.setSets(new Array('-LAYERS-', 'cbs', 'glad'));

  /* Layers */
  this.setChromosomeLayers(new Array('axes', 'cytoband', 'gridH'));
  this.setSampleLayers(new Array('CBS', 'GLAD', 'rawCNs'));

  /* Zooms */
  this.setZooms(new Array(1, 2, 4, 8, 16, 32, 64, 128));

  return(false);
}
